language: node_js
node_js:
  - "10"

dist: trusty
addons:
  chrome: stable

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
      script: npm run lint:format
    - stage: test
      script: npm run test:headless
    - stage: deploy
      script: npm run build:prod && (cd dist; zip --recurse-paths absenzenmanagement.zip *)
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        on:
          branch: master