language: node_js
node_js:
  - "10"

dist: trusty
addons:
  chrome: stable

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
      script: npm run lint:format
    - stage: test
      script: npm run test:headless
