language: node_js
node_js:
  - "10"

dist: trusty
addons:
  chrome: stable

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
      script: npm run lint:format
    - stage: test
      script: npm run test:headless
    - stage: deploy
      script: 
        - npm run build:prod
        - cp README.md dist && cp -r doc dist
        - (cd dist && zip --recurse-paths absenzenmanagement.zip *)
        - mv dist/absenzenmanagement dist/app
        - sed -e "s~https://eventotest.api~$API_URL~g" dist/app/settings.example.js > dist/app/settings.js
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        on:
          branch: master

stages:
  - lint
  - test
  - name: deploy
    if: branch = master